name: User Story
description: Nova funcionalidade descrita como User Story
title: "US-XX: "
labels: ["user-story"]
body:
  - type: textarea
    id: historia
    attributes:
      label: Historia
      value: |
        **Como** <perfil>
        **Quero** <acao>
        **Para** <beneficio>
    validations:
      required: true
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceite (Gherkin)
      value: |
        **Dado que** ...
        **Quando** ...
        **Entao** ...
    validations:
      required: true
  - type: input
    id: regras
    attributes:
      label: Regras de negocio envolvidas
      placeholder: RN01, RN03
  - type: dropdown
    id: perfil
    attributes:
      label: Perfil
      options: [Paciente, Atendente, Sistema]
    validations:
      required: true
